version: '2'
services:
    rfbloy-app:
        image: rfbloy
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://rfbloy-mysql:3306/rfbloy?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    rfbloy-mysql:
        extends:
            file: mysql.yml
            service: rfbloy-mysql
